openapi: 3.0.3
info:
  title: TouristApps API
  version: 1.0.0
  description: This is a touristApps official API documentation
paths:
  /api/concentrate/:
    get:
      operationId: api_concentrate_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConcentrateQuality'
          description: ''
    post:
      operationId: api_concentrate_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConcentrateQuality'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ConcentrateQuality'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ConcentrateQuality'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcentrateQuality'
          description: ''
  /api/concentrate/{id}/:
    get:
      operationId: api_concentrate_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this concentrate quality.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcentrateQuality'
          description: ''
    put:
      operationId: api_concentrate_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this concentrate quality.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConcentrateQuality'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ConcentrateQuality'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ConcentrateQuality'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcentrateQuality'
          description: ''
    patch:
      operationId: api_concentrate_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this concentrate quality.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedConcentrateQuality'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedConcentrateQuality'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedConcentrateQuality'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcentrateQuality'
          description: ''
    delete:
      operationId: api_concentrate_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this concentrate quality.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    ConcentrateQuality:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 20
        month:
          type: string
          maxLength: 20
        iron:
          type: number
          format: double
        silicon:
          type: number
          format: double
        aluminum:
          type: number
          format: double
        calcium:
          type: number
          format: double
        sulfur:
          type: number
          format: double
        user:
          type: integer
      required:
      - aluminum
      - calcium
      - id
      - iron
      - month
      - name
      - silicon
      - sulfur
      - user
    PatchedConcentrateQuality:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 20
        month:
          type: string
          maxLength: 20
        iron:
          type: number
          format: double
        silicon:
          type: number
          format: double
        aluminum:
          type: number
          format: double
        calcium:
          type: number
          format: double
        sulfur:
          type: number
          format: double
        user:
          type: integer
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
